spring.config.import=optional:file:./.env.properties

spring.thymeleaf.cache=false
spring.web.resources.cache.period=0
spring.web.resources.chain.cache=false

spring.devtools.livereload.enabled=true
spring.devtools.restart.enabled=true

spring.datasource.url=jdbc:h2:file:./data/movierecord;AUTO_SERVER=TRUE;NON_KEYWORDS=RANK
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.orm.jdbc.bind=trace

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

app.upload.dir=./uploads
